version: '3.9'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    environment:
      DB_HOST: db
      DB_USERNAME: user
      DB_PASSWORD: password
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOST: elasticsearch
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: password
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: prompt_finder_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
volumes:
  dbdata:
  esdata:
